### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by lrworth**
This essentially consists of the improvements made in https://github.com/Arguggi/haskell-cached-io.

## Maintainer 
[The Hackage page for cached-io](https://hackage.haskell.org/package/cached-io) lists a maintainer email address that bounces, and a GitHub repo that does not exist. We've started using this library and would like its maintenance to continue. If you are willing to continue its maintenance then please update the Hackage page, and consider accepting this PR and creating a new release. It would also be useful to enable the GitHub issue tracker.

[Bellroy](https://github.com/bellroy) is willing to support the ongoing maintenance of this project, either by contributing to this repository or by assuming ownership of the project altogether. Please let me know how you want to proceed.

### CODE REVIEW

**Comment by glasserc** [comment]
[Now that's a name I've not heard in a long time...](https://www.youtube.com/watch?v=Q3LE15AyT5g)

I think this was just my personal fork of the repo that was hosted by the organization itself (which I guess is gone now). I think the last four or five commits here (since 0e578d2f87d241557b1ed7e6b82d356370ae5c22) are probably garbage. I think the first few commits (by @rickowens, @pjrt, @MHova and @toddsundsted) all represent further development under the same organization that isn't in this fork for some reason. I don't have any context about the changes that Arguggi made.

I would be happy for another team to take over management of this project. I'm not exactly sure what the logistics of that would be. Certainly you can remove my old email address from the `maintainer` field of the `.cabal` file. I don't know if I have the legal rights to transfer ownership but it's an open source project so I think you can just take it over. I think I could add you as a maintainer for the Hackage package. I'm not sure if I can promote another fork of the project to be the "primary" one, but if I can I would be happy to do that too.

**Comment by toddsundsted** [comment]
my opinion counts for naught since i only authored a merge commit. :-)

**Comment by lrworth** [comment]
Alright, I've finally received legal approval for Bellroy to takeover this package. Thanks @glasserc for being willing to do this!

According to https://wiki.haskell.org/Taking_over_a_package, you just need to add https://hackage.haskell.org/user/Bellroy as a maintainer on the package and then we can upload a new version that sets the maintainer email address and github repo etc.

**Comment by glasserc** [comment]
OK, I added it! Let me know if it worked, or if there's something else I need to do!

**Comment by lrworth** [comment]
I've just released [cached-io-1.2.0.0](https://hackage.haskell.org/package/cached-io-1.2.0.0) 🎉

**Comment by lrworth** [comment]
@glasserc would you be OK with transferring ownership of this repo to Bellroy? We've had some internal discussion because people keep accidentally opening PRs against this repo when they meant to open against our fork. Our options are:
1. Status quo
2. @glasserc transfers ownership to @bellroy, and we merge all the commits from [our fork](https://github.com/bellroy/haskell-cached-io).
3. We [detach our fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork). I don't like this option because it forgets who originally wrote the library.

**Comment by glasserc** [comment]
Hmm, I guess Github doesn't track each fork of a repo against just its parent, but rather against one universal root? That's unfortunate and a little surprising.

I'm happy to transfer ownership. Let me try poking around in the Github settings!

**Comment by glasserc** [comment]
OK, I tried going to https://github.com/glasserc/haskell-cached-io/transfer, and filling out `bellroy` and typing in the signature, I got this error message:

`bellroy/haskell-cached-io already exists and You don’t have the permission to create public repositories on bellroy`

I tried adding @lrworth as a collaborator to this repository in case that gives you both the Bellroy access and the access to this repo that it needs to do the transfer. If that doesn't work, maybe I can transfer it to you and you can transfer it to Bellroy? I don't have a lot of experience with this and due to something important in my personal life, I don't have a ton of time to dig into this further or figure out what the best way forward is, but let me know what you need me to do and I'm happy to do it.

**Pull request closed without merging**
